name: Zenn Article Template
description: "Zenn記事のテンプレートを作成するためのフォームです。"
title: "[記事タイトル]"
labels: ["新規"]
assignees:
  - healthybamboo
body:
  - type: markdown
    attributes:
      value: |
        # Zenn記事テンプレート
        以下のフィールドに情報を入力してください。

  - type: input
    id: title
    attributes:
      label: タイトル
      description: 記事のタイトルを入力してください。
      placeholder: "記事タイトル"
    validations:
      required: true

  - type: input
    attributes:
      label: 記事概要
      description: 記事の内容を簡単に説明する概要を記入してください。
      placeholder: "記事の概要"

  - type: input
    attributes:
      label: 前提条件
      description: 読者が記事を理解するために必要な前提条件や知識を記載してください。
      placeholder: "前提条件"

  - type: textarea
    id: body
    attributes:
      label: 本文
      description: 記事の主要部分を書いてください。セクションごとに分けて、各セクションに見出しを追加してください。
      placeholder: "セクション1:\nセクション2:\nセクション3:"
    validations:
      required: false
     
  - type: input
    attributes:
      label: 参考リンク
      description: 記事に関連する参考リンクやリソースを記載してください。
      placeholder: "参考リンク"

