name: Zenn Article Template
description: "Zenn記事のテンプレートを作成するためのフォームです。"
title: "[記事タイトル]"
labels: ["新規"]
body:
  - type: markdown
    attributes:
      value: |
        # Zenn記事テンプレート
        以下のフィールドに情報を入力してください。
  - type: dropdown
    id: article_type
    attributes:
      label: 記事の種類
      description: "記事の種類を選択してください。\nhttps://zenn.dev/tech-or-idea"
      multiple: true
      options:
        - Tech
        - Idea

  - type: textarea
    attributes:
      label: 記事概要
      description: 記事の内容を簡単に説明する概要を記入してください。
      placeholder: "記事の概要"

  - type: textarea
    attributes:
      label: 前提条件
      description: 読者が記事を理解するために必要な前提条件や知識を記載してください。
      placeholder: "前提条件"

  - type: textarea
    id: body
    attributes:
      label: 本文
      description: 記事の主要部分を書いてください。セクションごとに分けて、各セクションに見出しを追加してください。
      placeholder: "セクション1:\nセクション2:\nセクション3:"
    validations:
      required: false

  - type: textarea
    attributes:
      label: 参考リンク
      description: 記事に関連する参考リンクやリソースを記載してください。
      placeholder: "参考リンク"
